### ISSUE TITLE
How is forward being called.

### ISSUE THREAD

**Issue by kris-singh** [Mjkim88/Pytorch-Torchtext-Seq2Seq#1]
Sorry this might be a dumb question.
In decoder.py In the definition you use self. decodercell = DecoderCell
You use the forward function of class DecoderCell to get the prev_s(The previously generated word) Right?
prev_s = self.decodercell(target[:, i], prev_s, ctx)
But shouldn't it be self.decodercell.forward(target[:, i], prev_s, ctx). 
Maybe i missed something but could you explain?

**Comment by Mjkim88** [comment]
Sorry for late reply.
Note that the class "DeocderCell" inherits the class "nn.Module", which calls "forward" when it is called after class initialization. Therefore, prev_s = self.decodercell(target[:,i], prev_s, ctx) actually calls the function forward.
